apiVersion: apps/v1
kind: Deployment
metadata:
   name: frontend-deployment
   labels:
      type: react-deployment
      app: fe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        type: frontend
    spec:
      containers:
      - name: pocketpay-frontend
        image: ghcr.io/paritosh-pranjal/bc-pocketpay-frontend-eks:2
        ports:
        - containerPort: 80
      imagePullSecrets: 
      - name: ghcr-secret